export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/index.html.js"), meta: {"title":"欢迎来到橘络人物分析文档"} }],
  ["/detailed-character-analysis/character-interaction-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_character-interaction-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/character-interaction-analysis.html.js"), meta: {"title":"📊 人物互动关系分析"} }],
  ["/detailed-character-analysis/document-navigation-map.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_document-navigation-map.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/document-navigation-map.html.js"), meta: {"title":"📚 文档导航地图"} }],
  ["/detailed-character-analysis/document-template.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_document-template.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/document-template.html.js"), meta: {"title":"[文档标题] - [分析类型]"} }],
  ["/detailed-character-analysis/final-integrated-analysis-report.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_final-integrated-analysis-report.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/final-integrated-analysis-report.html.js"), meta: {"title":"聊天记录最终整合分析报告"} }],
  ["/detailed-character-analysis/juluo-changting-luoyuwai-relationship-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-changting-luoyuwai-relationship-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-changting-luoyuwai-relationship-analysis.html.js"), meta: {"title":"橘络与长亭落雨外关系分析报告"} }],
  ["/detailed-character-analysis/juluo-happy-chocolate-relationship-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-happy-chocolate-relationship-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-happy-chocolate-relationship-analysis.html.js"), meta: {"title":"橘络与Happy、巧克力关系分析报告"} }],
  ["/detailed-character-analysis/juluo-overnight-dowen-relationship-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-overnight-dowen-relationship-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-overnight-dowen-relationship-analysis.html.js"), meta: {"title":"橘络与通宵倒问关系分析报告"} }],
  ["/detailed-character-analysis/juluo-relationship-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-relationship-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-relationship-analysis.html.js"), meta: {"title":"📋 橘络人际关系综合分析报告"} }],
  ["/detailed-character-analysis/juluo-wangxinrui-relationship-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-wangxinrui-relationship-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-wangxinrui-relationship-analysis.html.js"), meta: {"title":"橘络与Qr关系分析报告"} }],
  ["/detailed-character-analysis/", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/index.html.js"), meta: {"title":"详细人物分析文档库"} }],
  ["/detailed-character-analysis/uncle-liyuhang-changting-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_uncle-liyuhang-changting-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/uncle-liyuhang-changting-analysis.html.js"), meta: {"title":"大叔（李宇航）/长亭落雨外详细分析文档"} }],
  ["/detailed-character-analysis/%E6%A9%98%E7%BB%9C%E7%A4%BE%E4%BA%A4%E5%85%B3%E7%B3%BB%E5%85%A8%E6%99%AF%E5%88%86%E6%9E%90%E6%8A%A5%E5%91%8A.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_橘络社交关系全景分析报告.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/橘络社交关系全景分析报告.html.js"), meta: {"title":"橘络社交关系全景分析报告"} }],
  ["/detailed-character-analysis/%E6%A9%98%E7%BB%9C%E7%A4%BE%E4%BA%A4%E5%85%B3%E7%B3%BB%E7%BB%BC%E5%90%88%E5%AF%B9%E6%AF%94%E5%88%86%E6%9E%90%E6%8A%A5%E5%91%8A.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_橘络社交关系综合对比分析报告.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/橘络社交关系综合对比分析报告.html.js"), meta: {"title":"橘络社交关系综合对比分析报告"} }],
  ["/detailed-character-analysis/%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E7%BB%BC%E5%90%88%E5%88%86%E6%9E%90%E6%8A%A5%E5%91%8A.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_聊天记录综合分析报告.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/聊天记录综合分析报告.html.js"), meta: {"title":"聊天记录综合分析报告"} }],
  ["/detailed-character-analysis/%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E7%BB%BC%E5%90%88%E5%AF%B9%E6%AF%94%E5%88%86%E6%9E%90%E6%8A%A5%E5%91%8A.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_聊天记录综合对比分析报告.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/聊天记录综合对比分析报告.html.js"), meta: {"title":"聊天记录综合对比分析报告"} }],
  ["/resources/kamian.html", { loader: () => import(/* webpackChunkName: "resources_kamian.html" */"D:/github/api.juluo/.vuepress/.temp/pages/resources/kamian.html.js"), meta: {"title":"卡面展示"} }],
  ["/resources/lolita-clothing-illustrations.html", { loader: () => import(/* webpackChunkName: "resources_lolita-clothing-illustrations.html" */"D:/github/api.juluo/.vuepress/.temp/pages/resources/lolita-clothing-illustrations.html.js"), meta: {"title":"洛丽塔服装插画"} }],
  ["/resources/", { loader: () => import(/* webpackChunkName: "resources_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/resources/index.html.js"), meta: {"title":"资源库"} }],
  ["/resources/winter-tree-cg.html", { loader: () => import(/* webpackChunkName: "resources_winter-tree-cg.html" */"D:/github/api.juluo/.vuepress/.temp/pages/resources/winter-tree-cg.html.js"), meta: {"title":"冬季树木CG图库"} }],
  ["/tools/", { loader: () => import(/* webpackChunkName: "tools_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/tools/index.html.js"), meta: {"title":"实用工具"} }],
  ["/tools/terrasavr-plus.html", { loader: () => import(/* webpackChunkName: "tools_terrasavr-plus.html" */"D:/github/api.juluo/.vuepress/.temp/pages/tools/terrasavr-plus.html.js"), meta: {"title":"Terrasavr Plus - 字符存档编辑器"} }],
  ["/detailed-character-analysis/bros-chat-group/aiyisuifengqi-detailed-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_aiyisuifengqi-detailed-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/aiyisuifengqi-detailed-analysis.html.js"), meta: {"title":"爱意随风起详细分析文档"} }],
  ["/detailed-character-analysis/bros-chat-group/bros-chat-group-emotions-attitudes.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_bros-chat-group-emotions-attitudes.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/bros-chat-group-emotions-attitudes.html.js"), meta: {"title":"基友交流群♂ - 情绪与态度分析"} }],
  ["/detailed-character-analysis/bros-chat-group/bros-chat-group-interaction-patterns.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_bros-chat-group-interaction-patterns.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/bros-chat-group-interaction-patterns.html.js"), meta: {"title":"基友交流群♂ - 互动模式分析"} }],
  ["/detailed-character-analysis/bros-chat-group/bros-chat-group-themes-keywords.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_bros-chat-group-themes-keywords.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/bros-chat-group-themes-keywords.html.js"), meta: {"title":"基友交流群♂ - 核心主题与高频词分析"} }],
  ["/detailed-character-analysis/bros-chat-group/dowen-detailed-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_dowen-detailed-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/dowen-detailed-analysis.html.js"), meta: {"title":"🌙 通宵倒问详细分析文档"} }],
  ["/detailed-character-analysis/bros-chat-group/juluo-group-chat-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_juluo-group-chat-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/juluo-group-chat-analysis.html.js"), meta: {"title":"橘络详细分析文档"} }],
  ["/detailed-character-analysis/bros-chat-group/qialuoyi-detailed-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_qialuoyi-detailed-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/qialuoyi-detailed-analysis.html.js"), meta: {"title":"掐咯一详细分析文档"} }],
  ["/detailed-character-analysis/bros-chat-group/", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_bros-chat-group_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/bros-chat-group/index.html.js"), meta: {"title":"👥 基友交流群♂分析文档"} }],
  ["/detailed-character-analysis/dp-chat-group/dp-chat-group-emotions-attitudes.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_dp-chat-group_dp-chat-group-emotions-attitudes.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/dp-chat-group/dp-chat-group-emotions-attitudes.html.js"), meta: {"title":"DPの交流群 - 情绪与态度分析"} }],
  ["/detailed-character-analysis/dp-chat-group/dp-chat-group-interaction-patterns.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_dp-chat-group_dp-chat-group-interaction-patterns.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/dp-chat-group/dp-chat-group-interaction-patterns.html.js"), meta: {"title":"DPの交流群 - 互动模式分析"} }],
  ["/detailed-character-analysis/dp-chat-group/dp-chat-group-themes-keywords.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_dp-chat-group_dp-chat-group-themes-keywords.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/dp-chat-group/dp-chat-group-themes-keywords.html.js"), meta: {"title":"DPの交流群 - 核心主题与高频词分析"} }],
  ["/detailed-character-analysis/dp-chat-group/dp-detailed-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_dp-chat-group_dp-detailed-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/dp-chat-group/dp-detailed-analysis.html.js"), meta: {"title":"👤 DP详细分析文档"} }],
  ["/detailed-character-analysis/dp-chat-group/", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_dp-chat-group_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/dp-chat-group/index.html.js"), meta: {"title":"💻 DPの交流群分析文档"} }],
  ["/detailed-character-analysis/dp-chat-group/xiaoding-detailed-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_dp-chat-group_xiaoding-detailed-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/dp-chat-group/xiaoding-detailed-analysis.html.js"), meta: {"title":"Happy、巧克力详细分析文档"} }],
  ["/detailed-character-analysis/private-chat/dowen-private-chat-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_private-chat_dowen-private-chat-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/private-chat/dowen-private-chat-analysis.html.js"), meta: {"title":"👤 倒问-私人聊天分析"} }],
  ["/detailed-character-analysis/private-chat/juluo-private-chat-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_private-chat_juluo-private-chat-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/private-chat/juluo-private-chat-analysis.html.js"), meta: {"title":"👤 橘络-私人聊天分析"} }],
  ["/detailed-character-analysis/private-chat/private-chat-emotions-attitudes.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_private-chat_private-chat-emotions-attitudes.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/private-chat/private-chat-emotions-attitudes.html.js"), meta: {"title":"😊 私人聊天-情绪与态度分析"} }],
  ["/detailed-character-analysis/private-chat/private-chat-interaction-patterns.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_private-chat_private-chat-interaction-patterns.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/private-chat/private-chat-interaction-patterns.html.js"), meta: {"title":"🔄 私人聊天-互动模式分析"} }],
  ["/detailed-character-analysis/private-chat/private-chat-themes-keywords.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_private-chat_private-chat-themes-keywords.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/private-chat/private-chat-themes-keywords.html.js"), meta: {"title":"🔍 私人聊天-核心主题与高频词分析"} }],
  ["/detailed-character-analysis/private-chat/", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_private-chat_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/private-chat/index.html.js"), meta: {"title":"私人聊天分析文档"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-data-visualization-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_juluo-dowen-data-visualization-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-data-visualization-analysis.html.js"), meta: {"title":"橘络与倒问关系发展数据可视化与量化分析报告"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-interaction-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_juluo-dowen-interaction-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-interaction-analysis.html.js"), meta: {"title":"橘络与倒问互动关系详细分析文档"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-psychological-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_juluo-dowen-psychological-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-psychological-analysis.html.js"), meta: {"title":"橘络与倒问心理发展综合分析报告"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-relationship-guide.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_juluo-dowen-relationship-guide.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-relationship-guide.html.js"), meta: {"title":"橘络与倒问关系维护与发展实用指南"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-relationship-summary.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_juluo-dowen-relationship-summary.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-relationship-summary.html.js"), meta: {"title":"橘络与倒问关系分析总结报告"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-timeline-analysis.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_juluo-dowen-timeline-analysis.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/juluo-dowen-timeline-analysis.html.js"), meta: {"title":"橘络与倒问关系发展综合时间线分析报告"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/index.html.js"), meta: {"title":"橘络与倒问关系分析 - 文件夹说明"} }],
  ["/detailed-character-analysis/juluo-dowen-relationship-analysis/%E7%B4%A2%E5%BC%95.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_juluo-dowen-relationship-analysis_索引.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/juluo-dowen-relationship-analysis/索引.html.js"), meta: {"title":"橘络与倒问关系分析文件夹索引"} }],
  ["/detailed-character-analysis/thinking-process/analysis-thinking-records.html", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_thinking-process_analysis-thinking-records.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/thinking-process/analysis-thinking-records.html.js"), meta: {"title":"📝 分析思考记录"} }],
  ["/detailed-character-analysis/thinking-process/", { loader: () => import(/* webpackChunkName: "detailed-character-analysis_thinking-process_index.html" */"D:/github/api.juluo/.vuepress/.temp/pages/detailed-character-analysis/thinking-process/index.html.js"), meta: {"title":"💭 思考过程文档"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/github/api.juluo/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
